version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web/:/vol/web
    environment:
      - SECRET_KEY=secretkeydev
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=car_parts
      - DB_USER=bucefal99
      - DB_PASS=IvanIvanov990812
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=car_parts
      - POSTGRES_USER=bucefal99
      - POSTGRES_PASSWORD=IvanIvanov990812
